### ISSUE TITLE
 FileNotFoundError: [Errno 2] No such file or directory: '../../checkpoints/MetaQA/ComplEx_2.pt'

### ISSUE THREAD

**Issue by cdhx** [malllabiisc/EmbedKGQA#81]
runing first command, got this error

```
Traceback (most recent call last):
  File "/home2/xhuang/PycharmProject/EmbedKGQA/KGQA/LSTM/main.py", line 346, in <module>
    bn_list=bn_list)
  File "/home2/xhuang/PycharmProject/EmbedKGQA/KGQA/LSTM/main.py", line 228, in train
    torch.save(model.state_dict(), checkpoint_file_name)
  File "/home2/xhuang/.conda/envs/embedkgqa/lib/python3.7/site-packages/torch/serialization.py", line 260, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home2/xhuang/.conda/envs/embedkgqa/lib/python3.7/site-packages/torch/serialization.py", line 183, in _with_file_like
    f = open(f, mode)
FileNotFoundError: [Errno 2] No such file or directory: '../../checkpoints/MetaQA/ComplEx_2.pt'
```

**Comment by Jay-gethome** [comment]
This path is just the model's save path, you can add it by yourself

**Comment by Matcha-Cheese** [comment]
Hello, have you solved the issue? I am facing the same problem as well.
